pipeline:
  docker:
    image: plugins/docker
    repo: registry.liskl.com/tstllc/alpine-jenkins
    force_tag: true

publish:
  docker:
    repo: registry.liskl.com/tstllc/alpine-jenkins
    tag:
      - latest
    when:
      branch:
        include: [ master, release/* ]

publish:
  docker:
    repo: registry.liskl.com/tstllc/alpine-jenkins
    tag:
      - ${DRONE_BRANCH}-latest
      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
    when:
      branch:
        exclude: [ master ]
